---
name: flutter_insta_clone
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  enum_to_string: ^2.0.1
  meta: ^1.3.0
  cached_network_image: ^3.0.0
  cloud_firestore: ^1.0.6
  firebase_core: ^1.0.4
  firebase_analytics: ^8.0.1
  firebase_auth: ^1.1.1
  firebase_storage: ^8.0.4
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
  image_cropper: ^1.4.0
  image_picker: ^0.7.4
  intl: ^0.17.0
  timeago: ^3.0.2
  uuid: 3.0.4
  bot_toast: ^4.0.1
  font_awesome_flutter: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/images/auth/
